//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrayDuckMail.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrayDuckMail.Common.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray Duck Mail.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create database file..
        /// </summary>
        internal static string Exception_DBNotCreated {
            get {
                return ResourceManager.GetString("Exception_DBNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the formatting of the message..
        /// </summary>
        internal static string Exception_FormatNotDetermined {
            get {
                return ResourceManager.GetString("Exception_FormatNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file upload was not in the correct SQLite file format..
        /// </summary>
        internal static string Exception_MalformedDatabase {
            get {
                return ResourceManager.GetString("Exception_MalformedDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file uploaded is missing or was malformed..
        /// </summary>
        internal static string Exception_MalformedUpload {
            get {
                return ResourceManager.GetString("Exception_MalformedUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search term was provided..
        /// </summary>
        internal static string Exception_NoSearchTerm {
            get {
                return ResourceManager.GetString("Exception_NoSearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property selector was unable to resolve to a property name..
        /// </summary>
        internal static string Exception_PropertySelectorResolutionError {
            get {
                return ResourceManager.GetString("Exception_PropertySelectorResolutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating email wrapper object..
        /// </summary>
        internal static string Logger_CreatingEmailWrapper {
            get {
                return ResourceManager.GetString("Logger_CreatingEmailWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is a multipart message with at least one &apos;delivery-status&apos; section..
        /// </summary>
        internal static string Logger_DeliveryStatusDetected {
            get {
                return ResourceManager.GetString("Logger_DeliveryStatusDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting..
        /// </summary>
        internal static string Logger_Disconnecting {
            get {
                return ResourceManager.GetString("Logger_Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAP client disposing..
        /// </summary>
        internal static string Logger_DisposingIMAP {
            get {
                return ResourceManager.GetString("Logger_DisposingIMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POP3 Client disposing..
        /// </summary>
        internal static string Logger_DisposingPOP3 {
            get {
                return ResourceManager.GetString("Logger_DisposingPOP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing of the client wrapper object..
        /// </summary>
        internal static string Logger_DisposingWrapper {
            get {
                return ResourceManager.GetString("Logger_DisposingWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The discussion list is empty..
        /// </summary>
        internal static string Logger_EmptyDiscussionList {
            get {
                return ResourceManager.GetString("Logger_EmptyDiscussionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failed delivery was detected..
        /// </summary>
        internal static string Logger_FailedDeliveryDetected {
            get {
                return ResourceManager.GetString("Logger_FailedDeliveryDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bounced email contains a failure report, but an unknown recipient status group..
        /// </summary>
        internal static string Logger_FailureDetectedUnknownRecipient {
            get {
                return ResourceManager.GetString("Logger_FailureDetectedUnknownRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning Contact {0} to Discussion List {1}..
        /// </summary>
        internal static string Logger_Format_AssigningContact {
            get {
                return ResourceManager.GetString("Logger_Format_AssigningContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning index {0} to {1}..
        /// </summary>
        internal static string Logger_Format_AssigningMimeMessageIndex {
            get {
                return ResourceManager.GetString("Logger_Format_AssigningMimeMessageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating with {0}:{1}..
        /// </summary>
        internal static string Logger_Format_AuthenticatingWith {
            get {
                return ResourceManager.GetString("Logger_Format_AuthenticatingWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}:{1}..
        /// </summary>
        internal static string Logger_Format_ConnectingTo {
            get {
                return ResourceManager.GetString("Logger_Format_ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find contact with ID = {0}..
        /// </summary>
        internal static string Logger_Format_CouldNotFindContact {
            get {
                return ResourceManager.GetString("Logger_Format_CouldNotFindContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find discussion list with ID = {0}.
        /// </summary>
        internal static string Logger_Format_CouldNotFindDiscussionList {
            get {
                return ResourceManager.GetString("Logger_Format_CouldNotFindDiscussionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating db file at {0}..
        /// </summary>
        internal static string Logger_Format_CreatingDB {
            get {
                return ResourceManager.GetString("Logger_Format_CreatingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file created at {0}..
        /// </summary>
        internal static string Logger_Format_DBCreated {
            get {
                return ResourceManager.GetString("Logger_Format_DBCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create database file at {0}..
        /// </summary>
        internal static string Logger_Format_DBNotCreated {
            get {
                return ResourceManager.GetString("Logger_Format_DBNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting message {0}..
        /// </summary>
        internal static string Logger_Format_DeletingMessage {
            get {
                return ResourceManager.GetString("Logger_Format_DeletingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- {0}: {1}.
        /// </summary>
        internal static string Logger_Format_FailureStatusGroupsLine {
            get {
                return ResourceManager.GetString("Logger_Format_FailureStatusGroupsLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form input was malformed or missing for {0}..
        /// </summary>
        internal static string Logger_Format_FormInputMalformed {
            get {
                return ResourceManager.GetString("Logger_Format_FormInputMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unsubscription request for non-existant contact with ID {0}..
        /// </summary>
        internal static string Logger_Format_InvalidUnsubscriptionContact {
            get {
                return ResourceManager.GetString("Logger_Format_InvalidUnsubscriptionContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unsubscription request for non-existant discussion list with ID {0}..
        /// </summary>
        internal static string Logger_Format_InvalidUnsubscriptionDiscussionList {
            get {
                return ResourceManager.GetString("Logger_Format_InvalidUnsubscriptionDiscussionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unsubscription status for contact with ID {0} and discussion list {1} due to subscription status {2}..
        /// </summary>
        internal static string Logger_Format_InvalidUnsubscriptionSubscriptionStatus {
            get {
                return ResourceManager.GetString("Logger_Format_InvalidUnsubscriptionSubscriptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading assembly {0}..
        /// </summary>
        internal static string Logger_Format_LoadingAssembly {
            get {
                return ResourceManager.GetString("Logger_Format_LoadingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing fuzzy search: {0}.
        /// </summary>
        internal static string Logger_Format_PerformingFuzzySearch {
            get {
                return ResourceManager.GetString("Logger_Format_PerformingFuzzySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending onboarding email to {0} ({1})..
        /// </summary>
        internal static string Logger_Format_SendingOnboardingEmail {
            get {
                return ResourceManager.GetString("Logger_Format_SendingOnboardingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a notication to the discussion list owner that {0} ({1}) has requested access to {2}..
        /// </summary>
        internal static string Logger_Format_SendingOwnerNotification {
            get {
                return ResourceManager.GetString("Logger_Format_SendingOwnerNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the subscription confirmation email to {0} ({1})..
        /// </summary>
        internal static string Logger_Format_SendingSubscriptionConfirmation {
            get {
                return ResourceManager.GetString("Logger_Format_SendingSubscriptionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a test Owner Notification email to discussion list {0}..
        /// </summary>
        internal static string Logger_Format_SendingTest {
            get {
                return ResourceManager.GetString("Logger_Format_SendingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the subscription confirmation email to {0} ({1})..
        /// </summary>
        internal static string Logger_Format_SendingUnsubscriptionConfirmation {
            get {
                return ResourceManager.GetString("Logger_Format_SendingUnsubscriptionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving page &apos;{0}&apos;.
        /// </summary>
        internal static string Logger_Format_ServingPage {
            get {
                return ResourceManager.GetString("Logger_Format_ServingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template processed: {0}..
        /// </summary>
        internal static string Logger_Format_TemplateProcessed {
            get {
                return ResourceManager.GetString("Logger_Format_TemplateProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Contact {0} to Discussion List {1}..
        /// </summary>
        internal static string Logger_Format_UnassigningContact {
            get {
                return ResourceManager.GetString("Logger_Format_UnassigningContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} unsubscribing from {1}..
        /// </summary>
        internal static string Logger_Format_UserUnsubscribing {
            get {
                return ResourceManager.GetString("Logger_Format_UserUnsubscribing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found the following resource names in the assembly manifest:.
        /// </summary>
        internal static string Logger_FoundResources {
            get {
                return ResourceManager.GetString("Logger_FoundResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- {0}.
        /// </summary>
        internal static string Logger_FoundResourcesLine {
            get {
                return ResourceManager.GetString("Logger_FoundResourcesLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating an email..
        /// </summary>
        internal static string Logger_GeneratingEmail {
            get {
                return ResourceManager.GetString("Logger_GeneratingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting messages..
        /// </summary>
        internal static string Logger_GettingMessages {
            get {
                return ResourceManager.GetString("Logger_GettingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing database for controller..
        /// </summary>
        internal static string Logger_InitializingControllerDatabase {
            get {
                return ResourceManager.GetString("Logger_InitializingControllerDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unsubscription request. No subscription status found..
        /// </summary>
        internal static string Logger_InvalidUnsubscriptionSubscription {
            get {
                return ResourceManager.GetString("Logger_InvalidUnsubscriptionSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading main HTML email template..
        /// </summary>
        internal static string Logger_LoadingHTMLTemplate {
            get {
                return ResourceManager.GetString("Logger_LoadingHTMLTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesasge body determined to contain HTML..
        /// </summary>
        internal static string Logger_MessageContainsHTML {
            get {
                return ResourceManager.GetString("Logger_MessageContainsHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message body determined to contain plain text..
        /// </summary>
        internal static string Logger_MessageContainsPlainText {
            get {
                return ResourceManager.GetString("Logger_MessageContainsPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaying message to {0} ({1}).
        /// </summary>
        internal static string Logger_RelayingMessage {
            get {
                return ResourceManager.GetString("Logger_RelayingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is being processed from the designated external port. Request Origin: {0}.
        /// </summary>
        internal static string Logger_RequestOnExternalPort {
            get {
                return ResourceManager.GetString("Logger_RequestOnExternalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is being processed from the designated internal port..
        /// </summary>
        internal static string Logger_RequestOnInternalPort {
            get {
                return ResourceManager.GetString("Logger_RequestOnInternalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is being processed from an unknown port ({0})). The docker container is likely misconfigured. Remote Origin: {1}.
        /// </summary>
        internal static string Logger_RequestOnUnknownPort {
            get {
                return ResourceManager.GetString("Logger_RequestOnUnknownPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving assignments..
        /// </summary>
        internal static string Logger_SavingAssignments {
            get {
                return ResourceManager.GetString("Logger_SavingAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SMTP client is not connected. Connecting now..
        /// </summary>
        internal static string Logger_SMTPNotConnected {
            get {
                return ResourceManager.GetString("Logger_SMTPNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template read into memory..
        /// </summary>
        internal static string Logger_TemplateInMemory {
            get {
                return ResourceManager.GetString("Logger_TemplateInMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown client type was requested..
        /// </summary>
        internal static string Logger_UnknownClientType {
            get {
                return ResourceManager.GetString("Logger_UnknownClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using IMAP client..
        /// </summary>
        internal static string Logger_UsingIMAP {
            get {
                return ResourceManager.GetString("Logger_UsingIMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using POP3 client..
        /// </summary>
        internal static string Logger_UsingPOP3 {
            get {
                return ResourceManager.GetString("Logger_UsingPOP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is part of the &apos;{0}&apos; discussion list. You can unsubscribe by sending any message to &lt;a href=&apos;mailto:{1}&apos;&gt;{1}&lt;/a&gt;.
        /// </summary>
        internal static string Mail_Format_HTMLUnsubscribeEmailMessage {
            get {
                return ResourceManager.GetString("Mail_Format_HTMLUnsubscribeEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is part of the &apos;{0}&apos; discussion list. You can unsubscribe by clicking here: &lt;a href=&apos;{1}&apos;&gt;{1}&lt;/a&gt;.
        /// </summary>
        internal static string Mail_Format_HTMLUnsubscribeLinkMessage {
            get {
                return ResourceManager.GetString("Mail_Format_HTMLUnsubscribeLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; email list administator has invited you to participate. To confirm your subscription, simply reply to this e-mail. If you do not wish to participate, you can ignore this email..
        /// </summary>
        internal static string Mail_Format_OnboardingBody {
            get {
                return ResourceManager.GetString("Mail_Format_OnboardingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been invited to the &apos;{0}&apos; Email Discussion List.
        /// </summary>
        internal static string Mail_Format_OnboardingSubheading {
            get {
                return ResourceManager.GetString("Mail_Format_OnboardingSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to {0}.
        /// </summary>
        internal static string Mail_Format_OnboardingSubject {
            get {
                return ResourceManager.GetString("Mail_Format_OnboardingSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has requested access to the &apos;{0}&apos; Email Discussion List.
        /// </summary>
        internal static string Mail_Format_OwnerNotificationSubheading {
            get {
                return ResourceManager.GetString("Mail_Format_OwnerNotificationSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to join {0}.
        /// </summary>
        internal static string Mail_Format_OwnerNotificationSubject {
            get {
                return ResourceManager.GetString("Mail_Format_OwnerNotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Message from {1}.
        /// </summary>
        internal static string Mail_Format_Subject {
            get {
                return ResourceManager.GetString("Mail_Format_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Message from {0}.
        /// </summary>
        internal static string Mail_Format_SubjectReplace {
            get {
                return ResourceManager.GetString("Mail_Format_SubjectReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glad to have you. To send a message to everyone on the discussion list, just send an email to &lt;a href=&apos;mailto:{0}&apos;&gt;{0}&lt;/a&gt;. When you recieve a message from someone in the group, you can simply reply to that email and everyone on the discussion list will get a copy..
        /// </summary>
        internal static string Mail_Format_SubscriptionConfirmationBody {
            get {
                return ResourceManager.GetString("Mail_Format_SubscriptionConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been subscribed to the &apos;{0}&apos; Email Discussion List.
        /// </summary>
        internal static string Mail_Format_SubscriptionConfirmationSubheading {
            get {
                return ResourceManager.GetString("Mail_Format_SubscriptionConfirmationSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        internal static string Mail_Format_SubscriptionConfirmationSubject {
            get {
                return ResourceManager.GetString("Mail_Format_SubscriptionConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is part of the &apos;{0}&apos; discussion list. You can unsubscribe by sending any message to {1}..
        /// </summary>
        internal static string Mail_Format_TextUnsubscribeEmailMessage {
            get {
                return ResourceManager.GetString("Mail_Format_TextUnsubscribeEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is part of the &apos;{0}&apos; discussion list. You can unsubscribe by clicking here: {1}.
        /// </summary>
        internal static string Mail_Format_TextUnsubscribeLinkMessage {
            get {
                return ResourceManager.GetString("Mail_Format_TextUnsubscribeLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully unsubscribed from this discussion list. If you&apos;d ever like to resubscribe, send a message to &lt;a href=&apos;mailto:{0}&apos;&gt;{0}&lt;/a&gt;..
        /// </summary>
        internal static string Mail_Format_UnsubscriptionConfirmationBody {
            get {
                return ResourceManager.GetString("Mail_Format_UnsubscriptionConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will no longer recieve messages from the &apos;{0}&apos; Email Discussion List.
        /// </summary>
        internal static string Mail_Format_UnsubscriptionConfirmationSubheading {
            get {
                return ResourceManager.GetString("Mail_Format_UnsubscriptionConfirmationSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been unsubscribed from {0}..
        /// </summary>
        internal static string Mail_Format_UnsubscriptionConfirmationSubject {
            get {
                return ResourceManager.GetString("Mail_Format_UnsubscriptionConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string Mail_OnboardingHeading {
            get {
                return ResourceManager.GetString("Mail_OnboardingHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Mail_Owner {
            get {
                return ResourceManager.GetString("Mail_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please visit the the web administration interface to process this request..
        /// </summary>
        internal static string Mail_OwnerNotificationBody {
            get {
                return ResourceManager.GetString("Mail_OwnerNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion List Access Request.
        /// </summary>
        internal static string Mail_OwnerNotificationHeading {
            get {
                return ResourceManager.GetString("Mail_OwnerNotificationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for subscribing!.
        /// </summary>
        internal static string Mail_SubscriptionConfirmationHeading {
            get {
                return ResourceManager.GetString("Mail_SubscriptionConfirmationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to see you go..
        /// </summary>
        internal static string Mail_UnsubscriptionConfirmationHeading {
            get {
                return ResourceManager.GetString("Mail_UnsubscriptionConfirmationHeading", resourceCulture);
            }
        }
    }
}
