//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrayDuckMail.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrayDuckMail.Common.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray Duck Mail.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create database file..
        /// </summary>
        internal static string Exception_DBNotCreated {
            get {
                return ResourceManager.GetString("Exception_DBNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the formatting of the message..
        /// </summary>
        internal static string Exception_FormatNotDetermined {
            get {
                return ResourceManager.GetString("Exception_FormatNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file upload was not in the correct SQLite file format..
        /// </summary>
        internal static string Exception_MalformedDatabase {
            get {
                return ResourceManager.GetString("Exception_MalformedDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file uploaded is missing or was malformed..
        /// </summary>
        internal static string Exception_MalformedUpload {
            get {
                return ResourceManager.GetString("Exception_MalformedUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search term was provided..
        /// </summary>
        internal static string Exception_NoSearchTerm {
            get {
                return ResourceManager.GetString("Exception_NoSearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property selector was unable to resolve to a property name..
        /// </summary>
        internal static string Exception_PropertySelectorResolutionError {
            get {
                return ResourceManager.GetString("Exception_PropertySelectorResolutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding email definition to queue..
        /// </summary>
        internal static string Logger_AddingEmailDefinition {
            get {
                return ResourceManager.GetString("Logger_AddingEmailDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  using SSL.
        /// </summary>
        internal static string Logger_AppendUsingSSL {
            get {
                return ResourceManager.GetString("Logger_AppendUsingSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application stopped..
        /// </summary>
        internal static string Logger_ApplicationStopped {
            get {
                return ResourceManager.GetString("Logger_ApplicationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning email fetch loop..
        /// </summary>
        internal static string Logger_BeginningFetchLoop {
            get {
                return ResourceManager.GetString("Logger_BeginningFetchLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning onboarding loop..
        /// </summary>
        internal static string Logger_BeginningOnboarderLoop {
            get {
                return ResourceManager.GetString("Logger_BeginningOnboarderLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning email sender loop..
        /// </summary>
        internal static string Logger_BeginningSenderLoop {
            get {
                return ResourceManager.GetString("Logger_BeginningSenderLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing changes to database..
        /// </summary>
        internal static string Logger_CommittingChangesToDatabase {
            get {
                return ResourceManager.GetString("Logger_CommittingChangesToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating email wrapper object..
        /// </summary>
        internal static string Logger_CreatingEmailWrapper {
            get {
                return ResourceManager.GetString("Logger_CreatingEmailWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is a multipart message with at least one &apos;delivery-status&apos; section..
        /// </summary>
        internal static string Logger_DeliveryStatusDetected {
            get {
                return ResourceManager.GetString("Logger_DeliveryStatusDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting..
        /// </summary>
        internal static string Logger_Disconnecting {
            get {
                return ResourceManager.GetString("Logger_Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAP client disposing..
        /// </summary>
        internal static string Logger_DisposingIMAP {
            get {
                return ResourceManager.GetString("Logger_DisposingIMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POP3 Client disposing..
        /// </summary>
        internal static string Logger_DisposingPOP3 {
            get {
                return ResourceManager.GetString("Logger_DisposingPOP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing of the client wrapper object..
        /// </summary>
        internal static string Logger_DisposingWrapper {
            get {
                return ResourceManager.GetString("Logger_DisposingWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch email definition from queue..
        /// </summary>
        internal static string Logger_EmailDefinitionFetchFailure {
            get {
                return ResourceManager.GetString("Logger_EmailDefinitionFetchFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found an email definition in the shared memory queue..
        /// </summary>
        internal static string Logger_EmailDefinitionFound {
            get {
                return ResourceManager.GetString("Logger_EmailDefinitionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email fetcher shutting down..
        /// </summary>
        internal static string Logger_EmailFetcherShutdown {
            get {
                return ResourceManager.GetString("Logger_EmailFetcherShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sender shutting down..
        /// </summary>
        internal static string Logger_EmailSenderShutDown {
            get {
                return ResourceManager.GetString("Logger_EmailSenderShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The discussion list is empty..
        /// </summary>
        internal static string Logger_EmptyDiscussionList {
            get {
                return ResourceManager.GetString("Logger_EmptyDiscussionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failed delivery was detected..
        /// </summary>
        internal static string Logger_FailedDeliveryDetected {
            get {
                return ResourceManager.GetString("Logger_FailedDeliveryDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bounced email contains a failure report, but an unknown recipient status group..
        /// </summary>
        internal static string Logger_FailureDetectedUnknownRecipient {
            get {
                return ResourceManager.GetString("Logger_FailureDetectedUnknownRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching email defintion from queue..
        /// </summary>
        internal static string Logger_FetchingEmailDefinition {
            get {
                return ResourceManager.GetString("Logger_FetchingEmailDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering bounced messages..
        /// </summary>
        internal static string Logger_FilteringBouncedMessages {
            get {
                return ResourceManager.GetString("Logger_FilteringBouncedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address for {0} appears to no longer be active..
        /// </summary>
        internal static string Logger_Format_AddressNotActive {
            get {
                return ResourceManager.GetString("Logger_Format_AddressNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning Contact {0} to Discussion List {1}..
        /// </summary>
        internal static string Logger_Format_AssigningContact {
            get {
                return ResourceManager.GetString("Logger_Format_AssigningContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning index {0} to {1}..
        /// </summary>
        internal static string Logger_Format_AssigningMimeMessageIndex {
            get {
                return ResourceManager.GetString("Logger_Format_AssigningMimeMessageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating as {0}..
        /// </summary>
        internal static string Logger_Format_AuthenticatingAs {
            get {
                return ResourceManager.GetString("Logger_Format_AuthenticatingAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating with {0}:{1}..
        /// </summary>
        internal static string Logger_Format_AuthenticatingWith {
            get {
                return ResourceManager.GetString("Logger_Format_AuthenticatingWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}:{1}..
        /// </summary>
        internal static string Logger_Format_ConnectingTo {
            get {
                return ResourceManager.GetString("Logger_Format_ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}:{1}{2}.
        /// </summary>
        internal static string Logger_Format_ConnectingToSSL {
            get {
                return ResourceManager.GetString("Logger_Format_ConnectingToSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find contact with ID = {0}..
        /// </summary>
        internal static string Logger_Format_CouldNotFindContact {
            get {
                return ResourceManager.GetString("Logger_Format_CouldNotFindContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find discussion list with ID = {0}.
        /// </summary>
        internal static string Logger_Format_CouldNotFindDiscussionList {
            get {
                return ResourceManager.GetString("Logger_Format_CouldNotFindDiscussionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating db file at {0}..
        /// </summary>
        internal static string Logger_Format_CreatingDB {
            get {
                return ResourceManager.GetString("Logger_Format_CreatingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file created at {0}..
        /// </summary>
        internal static string Logger_Format_DBCreated {
            get {
                return ResourceManager.GetString("Logger_Format_DBCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create database file at {0}..
        /// </summary>
        internal static string Logger_Format_DBNotCreated {
            get {
                return ResourceManager.GetString("Logger_Format_DBNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting message {0}..
        /// </summary>
        internal static string Logger_Format_DeletingMessage {
            get {
                return ResourceManager.GetString("Logger_Format_DeletingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing database context using {0}..
        /// </summary>
        internal static string Logger_Format_EstablishingDatabaseContext {
            get {
                return ResourceManager.GetString("Logger_Format_EstablishingDatabaseContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- {0}: {1}.
        /// </summary>
        internal static string Logger_Format_FailureStatusGroupsLine {
            get {
                return ResourceManager.GetString("Logger_Format_FailureStatusGroupsLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch loop complete. Waiting {0}..
        /// </summary>
        internal static string Logger_Format_FetchLoopComplete {
            get {
                return ResourceManager.GetString("Logger_Format_FetchLoopComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering {0} messages..
        /// </summary>
        internal static string Logger_Format_FilteringCount {
            get {
                return ResourceManager.GetString("Logger_Format_FilteringCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering message {0}..
        /// </summary>
        internal static string Logger_Format_FilteringMessage {
            get {
                return ResourceManager.GetString("Logger_Format_FilteringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering messages for {0}..
        /// </summary>
        internal static string Logger_Format_FilteringMessages {
            get {
                return ResourceManager.GetString("Logger_Format_FilteringMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message {0} matches the filter criteria..
        /// </summary>
        internal static string Logger_Format_FilterMatch {
            get {
                return ResourceManager.GetString("Logger_Format_FilterMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form input was malformed or missing for {0}..
        /// </summary>
        internal static string Logger_Format_FormInputMalformed {
            get {
                return ResourceManager.GetString("Logger_Format_FormInputMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing exisiting database {0}..
        /// </summary>
        internal static string Logger_Format_ImportingExistingDatabase {
            get {
                return ResourceManager.GetString("Logger_Format_ImportingExistingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unsubscription request for non-existant contact with ID {0}..
        /// </summary>
        internal static string Logger_Format_InvalidUnsubscriptionContact {
            get {
                return ResourceManager.GetString("Logger_Format_InvalidUnsubscriptionContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unsubscription request for non-existant discussion list with ID {0}..
        /// </summary>
        internal static string Logger_Format_InvalidUnsubscriptionDiscussionList {
            get {
                return ResourceManager.GetString("Logger_Format_InvalidUnsubscriptionDiscussionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unsubscription status for contact with ID {0} and discussion list {1} due to subscription status {2}..
        /// </summary>
        internal static string Logger_Format_InvalidUnsubscriptionSubscriptionStatus {
            get {
                return ResourceManager.GetString("Logger_Format_InvalidUnsubscriptionSubscriptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading assembly {0}..
        /// </summary>
        internal static string Logger_Format_LoadingAssembly {
            get {
                return ResourceManager.GetString("Logger_Format_LoadingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message {0} (Index {1}) processed. Marked for deletion from the server..
        /// </summary>
        internal static string Logger_Format_MessageProcessed {
            get {
                return ResourceManager.GetString("Logger_Format_MessageProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboarding loop complete. Waiting {0}..
        /// </summary>
        internal static string Logger_Format_OnboarderLoopComplete {
            get {
                return ResourceManager.GetString("Logger_Format_OnboarderLoopComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing fuzzy search: {0}.
        /// </summary>
        internal static string Logger_Format_PerformingFuzzySearch {
            get {
                return ResourceManager.GetString("Logger_Format_PerformingFuzzySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing list {0}..
        /// </summary>
        internal static string Logger_Format_ProcessingList {
            get {
                return ResourceManager.GetString("Logger_Format_ProcessingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} messages..
        /// </summary>
        internal static string Logger_Format_ProcessingMessages {
            get {
                return ResourceManager.GetString("Logger_Format_ProcessingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing subscription message from {0}..
        /// </summary>
        internal static string Logger_Format_ProcessingSubscriptionMessage {
            get {
                return ResourceManager.GetString("Logger_Format_ProcessingSubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sender loop complete. Waiting {0}..
        /// </summary>
        internal static string Logger_Format_SenderLoopComplete {
            get {
                return ResourceManager.GetString("Logger_Format_SenderLoopComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending onboarding email to {0} ({1})..
        /// </summary>
        internal static string Logger_Format_SendingOnboardingEmail {
            get {
                return ResourceManager.GetString("Logger_Format_SendingOnboardingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a notication to the discussion list owner that {0} ({1}) has requested access to {2}..
        /// </summary>
        internal static string Logger_Format_SendingOwnerNotification {
            get {
                return ResourceManager.GetString("Logger_Format_SendingOwnerNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the subscription confirmation email to {0} ({1})..
        /// </summary>
        internal static string Logger_Format_SendingSubscriptionConfirmation {
            get {
                return ResourceManager.GetString("Logger_Format_SendingSubscriptionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a test Owner Notification email to discussion list {0}..
        /// </summary>
        internal static string Logger_Format_SendingTest {
            get {
                return ResourceManager.GetString("Logger_Format_SendingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the subscription confirmation email to {0} ({1})..
        /// </summary>
        internal static string Logger_Format_SendingUnsubscriptionConfirmation {
            get {
                return ResourceManager.GetString("Logger_Format_SendingUnsubscriptionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving page &apos;{0}&apos;.
        /// </summary>
        internal static string Logger_Format_ServingPage {
            get {
                return ResourceManager.GetString("Logger_Format_ServingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting {0} (ID {1}) as active. They have confirmed they control the email address by responding to the subscription confirmation email..
        /// </summary>
        internal static string Logger_Format_SettingActive {
            get {
                return ResourceManager.GetString("Logger_Format_SettingActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template processed: {0}..
        /// </summary>
        internal static string Logger_Format_TemplateProcessed {
            get {
                return ResourceManager.GetString("Logger_Format_TemplateProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Contact {0} to Discussion List {1}..
        /// </summary>
        internal static string Logger_Format_UnassigningContact {
            get {
                return ResourceManager.GetString("Logger_Format_UnassigningContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown user has requested access to {0}. An alert will be sent to the owner address alias..
        /// </summary>
        internal static string Logger_Format_UnknownUserRequestedAccess {
            get {
                return ResourceManager.GetString("Logger_Format_UnknownUserRequestedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender is unrecognized or unauthorized to participate in {0}. We&apos;ll log it and let the message be deleted..
        /// </summary>
        internal static string Logger_Format_UnrecognizedOrUnauthorized {
            get {
                return ResourceManager.GetString("Logger_Format_UnrecognizedOrUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- {0}.
        /// </summary>
        internal static string Logger_Format_UnrecognizedOrUnauthorizedDomainLine {
            get {
                return ResourceManager.GetString("Logger_Format_UnrecognizedOrUnauthorizedDomainLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding: {0}.
        /// </summary>
        internal static string Logger_Format_UnrecognizedOrUnauthorizedEncoding {
            get {
                return ResourceManager.GetString("Logger_Format_UnrecognizedOrUnauthorizedEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: {0} ({1}).
        /// </summary>
        internal static string Logger_Format_UnrecognizedOrUnauthorizedFrom {
            get {
                return ResourceManager.GetString("Logger_Format_UnrecognizedOrUnauthorizedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bounced email was recieved for an address that is not subscribed to {0}. Ignoring this message..
        /// </summary>
        internal static string Logger_Format_UnsubscribedBounce {
            get {
                return ResourceManager.GetString("Logger_Format_UnsubscribedBounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, who is already subscribed to {1}, has requested access again. Ignoring this message..
        /// </summary>
        internal static string Logger_Format_UserAlreadySubscribed {
            get {
                return ResourceManager.GetString("Logger_Format_UserAlreadySubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has requested access to {1}, but has previously been denied. Ignoring this request..
        /// </summary>
        internal static string Logger_Format_UserPreviouslyDenied {
            get {
                return ResourceManager.GetString("Logger_Format_UserPreviouslyDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has requested access to {1}. Because they have previously be associated with the discussion list, they will be subscribed..
        /// </summary>
        internal static string Logger_Format_UserPreviouslySubscribed {
            get {
                return ResourceManager.GetString("Logger_Format_UserPreviouslySubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} subscribing to {1}..
        /// </summary>
        internal static string Logger_Format_UserSubscribing {
            get {
                return ResourceManager.GetString("Logger_Format_UserSubscribing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} unsubscribing from {1}..
        /// </summary>
        internal static string Logger_Format_UserUnsubscribing {
            get {
                return ResourceManager.GetString("Logger_Format_UserUnsubscribing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using custom view layout: {0}.
        /// </summary>
        internal static string Logger_Format_UsingCustomView {
            get {
                return ResourceManager.GetString("Logger_Format_UsingCustomView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found the following resource names in the assembly manifest:.
        /// </summary>
        internal static string Logger_FoundResources {
            get {
                return ResourceManager.GetString("Logger_FoundResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- {0}.
        /// </summary>
        internal static string Logger_FoundResourcesLine {
            get {
                return ResourceManager.GetString("Logger_FoundResourcesLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating an email..
        /// </summary>
        internal static string Logger_GeneratingEmail {
            get {
                return ResourceManager.GetString("Logger_GeneratingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting messages..
        /// </summary>
        internal static string Logger_GettingMessages {
            get {
                return ResourceManager.GetString("Logger_GettingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing database for controller..
        /// </summary>
        internal static string Logger_InitializingControllerDatabase {
            get {
                return ResourceManager.GetString("Logger_InitializingControllerDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing shared memory object via static constructor..
        /// </summary>
        internal static string Logger_InitializingSharedMemory {
            get {
                return ResourceManager.GetString("Logger_InitializingSharedMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unsubscription request. No subscription status found..
        /// </summary>
        internal static string Logger_InvalidUnsubscriptionSubscription {
            get {
                return ResourceManager.GetString("Logger_InvalidUnsubscriptionSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading main HTML email template..
        /// </summary>
        internal static string Logger_LoadingHTMLTemplate {
            get {
                return ResourceManager.GetString("Logger_LoadingHTMLTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved a malformed EmailDefinition..
        /// </summary>
        internal static string Logger_MalformedEmailDefinition {
            get {
                return ResourceManager.GetString("Logger_MalformedEmailDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesasge body determined to contain HTML..
        /// </summary>
        internal static string Logger_MessageContainsHTML {
            get {
                return ResourceManager.GetString("Logger_MessageContainsHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message body determined to contain plain text..
        /// </summary>
        internal static string Logger_MessageContainsPlainText {
            get {
                return ResourceManager.GetString("Logger_MessageContainsPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages found..
        /// </summary>
        internal static string Logger_NoMessagesFound {
            get {
                return ResourceManager.GetString("Logger_NoMessagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No freshly created assignments waiting for onboarding..
        /// </summary>
        internal static string Logger_NoOnboardingAssignments {
            get {
                return ResourceManager.GetString("Logger_NoOnboardingAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboarder shutting down..
        /// </summary>
        internal static string Logger_OnboarderShutDown {
            get {
                return ResourceManager.GetString("Logger_OnboarderShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering service workers..
        /// </summary>
        internal static string Logger_RegisteringServiceWorkers {
            get {
                return ResourceManager.GetString("Logger_RegisteringServiceWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaying message to {0} ({1}).
        /// </summary>
        internal static string Logger_RelayingMessage {
            get {
                return ResourceManager.GetString("Logger_RelayingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is being processed from the designated external port. Request Origin: {0}.
        /// </summary>
        internal static string Logger_RequestOnExternalPort {
            get {
                return ResourceManager.GetString("Logger_RequestOnExternalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is being processed from the designated internal port..
        /// </summary>
        internal static string Logger_RequestOnInternalPort {
            get {
                return ResourceManager.GetString("Logger_RequestOnInternalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is being processed from an unknown port ({0})). The docker container is likely misconfigured. Remote Origin: {1}.
        /// </summary>
        internal static string Logger_RequestOnUnknownPort {
            get {
                return ResourceManager.GetString("Logger_RequestOnUnknownPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running application..
        /// </summary>
        internal static string Logger_RunningApplication {
            get {
                return ResourceManager.GetString("Logger_RunningApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving assignments..
        /// </summary>
        internal static string Logger_SavingAssignments {
            get {
                return ResourceManager.GetString("Logger_SavingAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SMTP client is not connected. Connecting now..
        /// </summary>
        internal static string Logger_SMTPNotConnected {
            get {
                return ResourceManager.GetString("Logger_SMTPNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the main application..
        /// </summary>
        internal static string Logger_StartingApplication {
            get {
                return ResourceManager.GetString("Logger_StartingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping the application..
        /// </summary>
        internal static string Logger_StoppingApplication {
            get {
                return ResourceManager.GetString("Logger_StoppingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template read into memory..
        /// </summary>
        internal static string Logger_TemplateInMemory {
            get {
                return ResourceManager.GetString("Logger_TemplateInMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown client type was requested..
        /// </summary>
        internal static string Logger_UnknownClientType {
            get {
                return ResourceManager.GetString("Logger_UnknownClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using IMAP client..
        /// </summary>
        internal static string Logger_UsingIMAP {
            get {
                return ResourceManager.GetString("Logger_UsingIMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using POP3 client..
        /// </summary>
        internal static string Logger_UsingPOP3 {
            get {
                return ResourceManager.GetString("Logger_UsingPOP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is part of the &apos;{0}&apos; discussion list. You can unsubscribe by sending any message to &lt;a href=&apos;mailto:{1}&apos;&gt;{1}&lt;/a&gt;.
        /// </summary>
        internal static string Mail_Format_HTMLUnsubscribeEmailMessage {
            get {
                return ResourceManager.GetString("Mail_Format_HTMLUnsubscribeEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is part of the &apos;{0}&apos; discussion list. You can unsubscribe by clicking here: &lt;a href=&apos;{1}&apos;&gt;{1}&lt;/a&gt;.
        /// </summary>
        internal static string Mail_Format_HTMLUnsubscribeLinkMessage {
            get {
                return ResourceManager.GetString("Mail_Format_HTMLUnsubscribeLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; email list administator has invited you to participate. To confirm your subscription, simply reply to this e-mail. If you do not wish to participate, you can ignore this email..
        /// </summary>
        internal static string Mail_Format_OnboardingBody {
            get {
                return ResourceManager.GetString("Mail_Format_OnboardingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been invited to the &apos;{0}&apos; Email Discussion List.
        /// </summary>
        internal static string Mail_Format_OnboardingSubheading {
            get {
                return ResourceManager.GetString("Mail_Format_OnboardingSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to {0}.
        /// </summary>
        internal static string Mail_Format_OnboardingSubject {
            get {
                return ResourceManager.GetString("Mail_Format_OnboardingSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has requested access to the &apos;{0}&apos; Email Discussion List.
        /// </summary>
        internal static string Mail_Format_OwnerNotificationSubheading {
            get {
                return ResourceManager.GetString("Mail_Format_OwnerNotificationSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to join {0}.
        /// </summary>
        internal static string Mail_Format_OwnerNotificationSubject {
            get {
                return ResourceManager.GetString("Mail_Format_OwnerNotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Message from {1}.
        /// </summary>
        internal static string Mail_Format_Subject {
            get {
                return ResourceManager.GetString("Mail_Format_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Message from {0}.
        /// </summary>
        internal static string Mail_Format_SubjectReplace {
            get {
                return ResourceManager.GetString("Mail_Format_SubjectReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glad to have you. To send a message to everyone on the discussion list, just send an email to &lt;a href=&apos;mailto:{0}&apos;&gt;{0}&lt;/a&gt;. When you recieve a message from someone in the group, you can simply reply to that email and everyone on the discussion list will get a copy..
        /// </summary>
        internal static string Mail_Format_SubscriptionConfirmationBody {
            get {
                return ResourceManager.GetString("Mail_Format_SubscriptionConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been subscribed to the &apos;{0}&apos; Email Discussion List.
        /// </summary>
        internal static string Mail_Format_SubscriptionConfirmationSubheading {
            get {
                return ResourceManager.GetString("Mail_Format_SubscriptionConfirmationSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        internal static string Mail_Format_SubscriptionConfirmationSubject {
            get {
                return ResourceManager.GetString("Mail_Format_SubscriptionConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is part of the &apos;{0}&apos; discussion list. You can unsubscribe by sending any message to {1}..
        /// </summary>
        internal static string Mail_Format_TextUnsubscribeEmailMessage {
            get {
                return ResourceManager.GetString("Mail_Format_TextUnsubscribeEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is part of the &apos;{0}&apos; discussion list. You can unsubscribe by clicking here: {1}.
        /// </summary>
        internal static string Mail_Format_TextUnsubscribeLinkMessage {
            get {
                return ResourceManager.GetString("Mail_Format_TextUnsubscribeLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully unsubscribed from this discussion list. If you&apos;d ever like to resubscribe, send a message to &lt;a href=&apos;mailto:{0}&apos;&gt;{0}&lt;/a&gt;..
        /// </summary>
        internal static string Mail_Format_UnsubscriptionConfirmationBody {
            get {
                return ResourceManager.GetString("Mail_Format_UnsubscriptionConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will no longer recieve messages from the &apos;{0}&apos; Email Discussion List.
        /// </summary>
        internal static string Mail_Format_UnsubscriptionConfirmationSubheading {
            get {
                return ResourceManager.GetString("Mail_Format_UnsubscriptionConfirmationSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been unsubscribed from {0}..
        /// </summary>
        internal static string Mail_Format_UnsubscriptionConfirmationSubject {
            get {
                return ResourceManager.GetString("Mail_Format_UnsubscriptionConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string Mail_OnboardingHeading {
            get {
                return ResourceManager.GetString("Mail_OnboardingHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Mail_Owner {
            get {
                return ResourceManager.GetString("Mail_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please visit the the web administration interface to process this request..
        /// </summary>
        internal static string Mail_OwnerNotificationBody {
            get {
                return ResourceManager.GetString("Mail_OwnerNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion List Access Request.
        /// </summary>
        internal static string Mail_OwnerNotificationHeading {
            get {
                return ResourceManager.GetString("Mail_OwnerNotificationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for subscribing!.
        /// </summary>
        internal static string Mail_SubscriptionConfirmationHeading {
            get {
                return ResourceManager.GetString("Mail_SubscriptionConfirmationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to see you go..
        /// </summary>
        internal static string Mail_UnsubscriptionConfirmationHeading {
            get {
                return ResourceManager.GetString("Mail_UnsubscriptionConfirmationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string View_Administration_Heading {
            get {
                return ResourceManager.GetString("View_Administration_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform specialized tasks to manage and maintain your service here..
        /// </summary>
        internal static string View_Administration_Subheading {
            get {
                return ResourceManager.GetString("View_Administration_Subheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string View_Administration_Title {
            get {
                return ResourceManager.GetString("View_Administration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Settings.
        /// </summary>
        internal static string View_Administration_WebSettings {
            get {
                return ResourceManager.GetString("View_Administration_WebSettings", resourceCulture);
            }
        }
    }
}
